name: Build and Publish Flask Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write 
  contents: read 

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag flask-container-on-azure-app-service:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: jibinpb/flask-container-on-azure-app-service:latest

  publish:

    runs-on: ubuntu-latest
    environment: dev
    needs: [build]

    steps:
      - name: Azure Login
        uses: Azure/login@v1.5.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az account show
          az webapp create --resource-group pp-project-sandbox-rg \
            --plan pp-project-sandbox-asp \
            --name jibin-flask-container-on-azure-app-service \
            --deployment-container-image-name jibinpb/flask-container-on-azure-app-service:latest
      
  
